name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'
          cache: 'npm'
          cache-dependency-path: 'e2e/package-lock.json'

      - name: List directory contents of e2e folder
        run: ls -la e2e

      - name: Install e2e dependencies
        working-directory: ./e2e
        run: npm ci || npm install

      - name: Install Playwright browsers
        working-directory: ./e2e
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: ./e2e
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            e2e/playwright-report/
            e2e/test-results/
          retention-days: 30
